### ISSUE TITLE
AU files not showing up on mac.

### ISSUE THREAD

**Issue by shayneoneill** [AudioKit/AudioKitNet#1]
Not sure if this is the best place for support ,, but here goes!

I've installed the two AU .component files both in 
/Library/Audio/Plug-Ins/Components
and /Users/shayneoneill/Library/Audio/Plug-Ins/Components

After starting up logic, these didn't appear. So I logged out of logic, and deleted the AudioUnit cache, as one does if an AU file isn't playing nice with Logic, and this too didn't seem to get the AudioUnits showing up. 

Neither show up in Ableton Live either. 

I'm running MacOS High Sierra (No Mojave, running 2011 MBP/16gig ram). Are these only 32bit plugs? Or might there be some other issue affecting compatibility?

**Comment by getdunne** [comment]
Hi Shayne. This is an issue that arose in High Sierra. Log out and back in again, and your plugins will show up. I'd advise against putting copies of the same plugins in two places.

**Comment by shayneoneill** [comment]
Yes! It worked! I dont know why. Can I sugest either updating the documentation to mention this, or maybe I'll throw a pull request. But not today. 

Thanks for your assistance. This is the "Have you tried turning it off and on again" solution, and despite my best knowledge, it turns out thats what it is. Thanks!

**Comment by getdunne** [comment]
@shayneoneill Nobody knows why, and Apple won't say.
README at http://netvst.org/wiki/doku.php?id=downloading_and_using_netvst#installing updated.
